name: firtname
on: push
jobs:
  job1:
    name: firstjob
    runs-on: ubuntu-latest
    steps: 
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: timedatectl
  job2:
    name: secondjob
    runs-on: windows-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: Get-Date
  job3:
    name: thirdjob
    runs-on: macos-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: "date +%F"
  job4:
    name: fourthjob
    needs: [job1, job2, job3]
    runs-on: windows-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: Get-Date
